### ISSUE TITLE
Problem with subgrammars

### ISSUE THREAD

**Issue by Faulik** [erezsh/plyplus#18]
Python 3.4.1 with plyplus 0.6.1.
I'm trying to use https://github.com/erezsh/plyplus/blob/master/plyplus/grammars/config.g grammar and ini:
```ini
[GRAPHICS]
width=640
height=480

[MAP]
x_location=0
y_location=0
width=48
height=48
path=
autoload=1
vertical_shift=100

[MINIMAP]
size=128

[AMBIENT_OCCLUSION]
use_ambient_occlusion=yes
relative_tile_width=8.000000
ray_cast_distance=3
```
while it goes without errors it don`t build the correct tree.
```python
>>> t.select('section > start > name *')
STreeCollection[]
```
With graphviz(but with pydotplus 2.0.2, normal don't wont to work on newest python) i see that the main grammar was opened but not the subs.
![calling_popen2](https://cloud.githubusercontent.com/assets/749225/5878292/70a04678-a32e-11e4-9536-d74c82a58ae6.png)

Also i found that in https://github.com/erezsh/plyplus/blob/master/README.md you open your file with 
` t = g.parse(file(r"C:\Python2...npymath.ini").read())` and not with `open(file_name).read()`. This is intentional and i miss some other lib, or it's typo?

**Comment by Faulik** [comment]
Also from the source i got this problem:
Grammar:
```
start: (NEWLINE|comment|objects)+;
objects: OBJECT_STM NEWLINE (object)+;
OBJECT_STM: '\[OBJECT:[\w_]+\]';
object:  OBJECT NEWLINE tokens;

tokens: (comment|token)*;
token: TOKEN (NEWLINE)*;

OBJECT: '\[ITEM_[\w_:]+\]'
{
    start: '\[ITEM_' token_type ':' token_item_name '\]';
    token_type: '[\w_]+';
    token_item_name: '[\w_]+';
};

TOKEN: '\[[\w_ :]+\]'
{
    start: '\[' token_name options '\]';
    token_name: '[A-Z_]+';
    @options: (':' token_elem)*;
    token_elem: '[a-z_ ]+';
};

comment:'[\w ,\'_.]+';
NEWLINE: '[\n\r\t]+' (%newline) ;
```
and text:
```
item_pants

[OBJECT:ITEM]

[ITEM_PANTS:ITEM_PANTS_PANTS]
[PREPLURAL:pairs of]
[NAME:trousers:trousers]
[LBSTEP:MAX]
[STRUCTURAL_ELASTICITY_WOVEN_THREAD]
```
I got only the last thing is actually parsed in to subtree:
![calling_popen](https://cloud.githubusercontent.com/assets/749225/5878387/09b5c89c-a32f-11e4-9748-a0b1c477608d.png)

**Comment by erezsh** [comment]
Hi Faulik.
The short answer is you should load the grammars like this:  g=plyplus.Grammar(c, auto_filter_tokens=False).

The long answer is that there is a basic mechanism in plyplus to filter out "noise" tokens (for example in "a+(b)" the brackets are useless after parsing). The mechanism works this way: In rules that are dedicated to a single token, keep the token (for example: "plus: PLUS"), but otherwise remove all tokens. So in our example, it would parse as "var plus LPAR var RPAR" and plyplus will get rid of the parenthesis while keeping the plus sign).
So one thing you could do is rewrite your grammar so that everything that is important to you (SECTION, OPTION, VALUE) is protected within it's own rule. The other thing you can do is add the auto_filter_tokens option, which disables that mechanism and keeps ALL tokens. It means you will have to clean-up the tree for yourself (or search it more carefully), but all of your important values will be there.

I hope this helps,
Erez
