### ISSUE TITLE
What is correct grammar for parsing linear equations?

### ISSUE THREAD

**Issue by pertsev** [erezsh/plyplus#40]
Hi. I'm use follow grammar for every part of equation:
```
list_parser = Grammar("""
start: ( a | b )+;

// terminals
number: '\d+';
identifier: 'x';
add: '\+' | '-';
mul: '\*';
div: '/';

// non-terminals
@factor: identifier | number;
a: add? factor ((mul | div) factor)*;
b: add? number (div number)*;
""")
```
It's correct for follow input:
`print list_parser.parse('-5-2*x').pretty()`
```
start
  b
    add	-
    number	5
  a
    add	-
    number	2
    mul	*
    identifier	x

```
But follow:
`print list_parser.parse('-5-2/3*x').pretty()`
gives an error:
```
Traceback (most recent call last):
  File ".../LALR.py", line 37, in <module>
    print list_parser.parse('-5-2/3*x').pretty()
  File "...\python27\lib\site-packages\plyplus\plyplus.py", line 575, in parse
    return self._grammar.parse(text)
  File "...\python27\lib\site-packages\plyplus\plyplus.py", line 700, in parse
    tree = self.engine.parse(text)
  File "...\python27\lib\site-packages\plyplus\engine_ply.py", line 105, in parse
    raise ParseError(self.errors)
plyplus.common.ParseError: Syntax error in input at '*' (type _ANON_4) line 1 col 7
```
I think in my rule `a: add? factor ((mul | div) factor)*;`, the `((mul | div) factor)*` must match `/3` at first and `*x` after. 
What is problem here? Or, please, show me true way to give coefficients `a` and `b` form input string.

**Comment by pertsev** [comment]
I suppose the parser use a rule `b` instead `a`, but how to fix this?

**Comment by erezsh** [comment]
Hi,
Have you looked at the calc example? https://github.com/erezsh/plyplus/blob/master/examples/calc.py
It might be an easier starting point for you, because it successfully parses all arithmetic expressions.
You can then extract variables by running .select() queries on the AST.

Hint: Sometimes it's easier to build a very accepting parser, and validate correctness afterwards.

If you need a very different approach, please be more specific about your end goal.

Anyway, the issues are not the proper place for personal questions, so I'm going to close this issue.
If you need any more help, you're very welcome to email me. (erezshin+plyplus at gmail com)
