### ISSUE TITLE
Error parsing \forall

### ISSUE THREAD

**Issue by moneyburner99** [erezsh/plyplus#44]
text to parse is "\forall cinc"

Code is:

```
import plyplus

path = "Latex/sample_mip3.tex"
with open(path) as f:
    content = f.read()

    grammer = plyplus.Grammar(r"""

    @start: quant ;
    quant : '\\forall' string ;
    string : '[A-Za-z][A-Za-z0-9]*' ;
    WS: '[ \t\n]+' (%ignore) (%newline);


    """)
    print(grammer.parse(content))
```

Fails with Error:
plyplus.common.TokenizeError: Illegal character in input: '\forall cinc
', line: 1, error

however if i change \forall to \a everything is fine. It seems to have a problem with the string forall? What is going there?

**Comment by erezsh** [comment]
My guess is that this happens because \f is a special character is regexps, while \a isn't.
IIRC, try to use '\\\\' in to signify a backslash and see if it works.

**Comment by moneyburner99** [comment]
It doesn't work, my workaround is now to replace all \ with something like # before parsing.

**Comment by erezsh** [comment]
That's unfortunate!
You should check out my new parsing library, Lark: https://github.com/erezsh/lark
It can do most of what plyplus does (and a lot more), and it's already reasonably stable. If you try it, I recommend checking out the `master` branch (instead of pip install), because I made a lot of improvements lately and I haven't yet created a release.

**Comment by jmgnc** [comment]
Might want to mention lark in plyplus's README.md if that's the recommended route.

**Comment by erezsh** [comment]
Good idea, sorry it slipped my mind.
